
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[311] =
    {   0,
        0,    0,   91,   89,    2,    1,   81,   89,   74,   89,
       46,   47,   70,   72,   53,   73,   54,   71,   84,   52,
       75,   55,   76,   88,   50,   51,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   48,   89,   49,   80,    0,
       86,   82,   56,   57,   85,    0,   85,   84,   77,   79,
       78,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   36,   88,   88,   88,   88,
       88,   16,   88,   88,   88,   88,   88,   88,   88,   88,
       14,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   83,   87,    0,
        3,   85,   65,   88,   88,   88,   88,   88,   88,   59,
       88,   88,   88,   88,   88,   88,   88,   88,   17,   88,
       88,    4,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   58,   88,   88,   88,   88,   60,
       88,   88,   88,   88,   88,   88,   62,   37,   88,   61,
       63,   88,   39,   88,   88,   18,   19,   88,   40,   88,
       88,   41,   88,   42,   43,   88,   44,   88,   88,   69,
       88,   88,   88,   88,   88,   38,   88,   64,   88,   88,
       88,   88,   21,   88,   45,   88,   88,   88,   88,   22,

       66,   88,   88,   88,   88,   88,   88,   88,   20,   88,
       88,   88,   23,   88,   88,   88,   88,   88,   88,    9,
        5,   88,   88,   88,   88,   88,   88,   88,    8,   67,
       88,   88,   88,    6,   88,   88,   88,   88,   88,   88,
       12,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       11,   68,   88,   26,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,    7,   15,   27,   88,   24,
       88,   88,   88,   88,   10,   88,   88,   88,   88,   88,
       35,   34,   25,   88,   88,   88,   88,   88,   88,   88,
       88,   31,   88,   88,   88,   88,   88,   88,   88,   88,

       33,   13,   28,   88,   32,   88,   88,   30,   29,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       23,   24,   25,    1,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    1,    1,    1,
        1,    2,    1,    3,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[315] =
    {   0,
        0,    0,  186,  969,  969,  969,  150,  155,  969,  134,
      969,  969,  969,  116,  969,  107,   40,  107,   44,  969,
       93,   87,   82,   46,  969,  969,   48,   51,   54,   58,
       62,   64,   66,   88,   93,   95,   98,   56,  100,  102,
      107,  112,  104,  127,  134,  969,   43,  969,  969,   85,
      969,  969,  969,  969,  136,   81,  140,  145,  969,  969,
      969,    0,  147,  149,  151,  156,  158,  160,  162,  164,
      166,  168,  174,  180,  184,    0,  186,  189,  193,  196,
      198,  200,  210,  215,  219,  221,  226,  231,  235,  238,
      242,  246,  250,  252,  254,  256,  258,  260,  263,  270,

      277,  283,  285,  287,  289,  291,  294,  969,  969,   66,
      969,  296,  299,  303,  310,  312,  314,  316,  321,  323,
      325,  327,  329,  336,  341,  343,  346,  348,  354,  356,
      358,  361,  363,  365,  367,  369,  375,  377,  379,  382,
      384,  395,  392,  401,  410,  412,  414,  416,  420,  423,
      425,  428,  431,  433,  435,  437,  443,  449,  451,  453,
      456,  458,  460,  464,  466,  468,  470,  473,  475,  478,
      481,  483,  489,  493,  495,  498,  500,  502,  504,  510,
      512,  514,  516,  525,  527,  529,  531,  533,  537,  539,
      542,  547,  549,  552,  554,  558,  562,  564,  566,  568,

      572,  574,  581,  583,  585,  589,  595,  597,  599,  606,
      608,  613,  615,  617,  619,  625,  621,  627,  630,  641,
      645,  647,  650,  654,  656,  658,  660,  665,  662,  667,
      669,  671,  673,  677,  680,  690,  693,  695,  700,  702,
      704,  707,  709,  711,  716,  720,  722,  729,  731,  735,
      737,  742,  745,  749,  752,  754,  756,  761,  763,  767,
      769,  771,  773,  781,  783,  785,  789,  795,  799,  801,
      804,  807,  815,  818,  820,  822,  824,  826,  828,  830,
      834,  837,  840,  843,  846,  848,  850,  857,  860,  862,
      868,  870,  878,  880,  882,  888,  893,  885,  895,  897,

      899,  902,  906,  913,  915,  918,  923,  925,  927,  969,
      963,   64,  965,   57
    } ;

static yyconst flex_int16_t yy_def[315] =
    {   0,
      310,    1,  310,  310,  310,  310,  310,  311,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  312,  310,  310,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  310,  310,  310,  310,  311,
      310,  310,  310,  310,  310,  313,  310,  310,  310,  310,
      310,  314,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  314,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  310,  310,  313,
      310,  310,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,    0,
      310,  310,  310,  310
    } ;

static yyconst flex_int16_t yy_nxt[1025] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    4,   26,   24,   27,   24,   28,   29,
       30,   31,   24,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   24,   41,   42,   43,   44,   24,   45,   24,
       24,   24,   46,   47,   48,   55,   55,   57,   62,   58,
       58,   62,   62,   62,   62,   63,   62,   62,  111,   62,
       62,   62,   62,   62,   62,   64,   65,   62,   76,   62,
       62,   62,   62,  111,   66,   70,   90,   67,   77,  109,
       72,   71,   68,   69,   73,   74,  108,   82,   78,   79,

       81,   61,   80,   62,   62,   83,   60,   75,   62,   62,
       62,   62,   59,   62,   62,   62,   62,   62,   62,   62,
       62,   56,   62,   62,   84,   86,   54,   62,   62,   85,
      102,   87,   88,   94,  103,   53,   92,   95,   89,   91,
       52,   96,   62,   62,  104,   93,   97,  105,   98,   62,
       62,   55,   55,   99,  100,  112,  112,  101,   57,   51,
       58,   58,   62,   62,   62,   62,   62,   62,  106,   49,
      107,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,  310,  115,  310,  118,   62,
       62,  114,  116,  113,  117,   62,   62,  310,  121,   62,

       62,   62,   62,  310,   62,   62,  310,  119,   62,   62,
      120,   62,   62,   62,   62,   62,   62,  310,  125,  127,
      122,  310,  123,  126,  124,   62,   62,  310,  130,  310,
       62,   62,  310,  128,   62,   62,   62,   62,  310,  129,
      310,   62,   62,  310,  131,  133,   62,   62,  310,  134,
       62,   62,  135,   62,   62,  132,  136,   62,   62,  310,
      137,   62,   62,  310,  139,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,  310,   62,   62,
      310,  138,  143,  310,  141,   62,   62,  310,  144,  147,
      146,  142,   62,   62,  310,  140,  310,  145,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,  310,   62,
       62,  112,  112,  148,   62,   62,  310,  155,   62,   62,
      149,  310,  150,  153,  156,   62,   62,   62,   62,   62,
       62,   62,   62,  152,  151,  154,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,  310,  157,  310,  162,
      159,   62,   62,  160,  164,  161,   62,   62,   62,   62,
      158,   62,   62,   62,   62,  310,  166,  310,  165,   62,
       62,   62,   62,   62,   62,  163,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,  167,  168,  170,  310,
       62,   62,   62,   62,   62,   62,  169,   62,   62,   62,

       62,  310,  171,  173,  178,  310,  172,   62,   62,  310,
       62,   62,  176,  174,  310,  175,   62,   62,  310,  177,
      181,  179,  180,  182,  183,   62,   62,   62,   62,   62,
       62,   62,   62,  310,  185,   62,   62,  184,   62,   62,
       62,   62,  187,   62,   62,  310,   62,   62,   62,   62,
       62,   62,   62,   62,  189,  310,  191,  192,   62,   62,
      310,  188,  186,  193,   62,   62,   62,   62,   62,   62,
      190,   62,   62,   62,   62,   62,   62,  196,  194,   62,
       62,   62,   62,   62,   62,   62,   62,  195,   62,   62,
       62,   62,  199,   62,   62,  197,   62,   62,   62,   62,

      310,  198,  310,  200,   62,   62,  310,  202,   62,   62,
       62,   62,  310,   62,   62,   62,   62,   62,   62,   62,
       62,  201,  310,  203,  204,   62,   62,   62,   62,   62,
       62,   62,   62,  310,  207,  310,  205,  310,  208,  206,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
      310,  211,   62,   62,   62,   62,  210,   62,   62,  209,
      310,  213,   62,   62,   62,   62,  215,   62,   62,   62,
       62,  310,  212,   62,   62,  216,  214,   62,   62,   62,
       62,   62,   62,   62,   62,  310,  217,   62,   62,   62,
       62,  310,  220,  310,  221,  218,   62,   62,   62,   62,

       62,   62,  310,  219,   62,   62,  310,  224,  310,  222,
       62,   62,   62,   62,   62,   62,  310,  223,  310,  227,
      228,   62,   62,   62,   62,  226,  225,  310,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,  229,  232,
       62,   62,   62,   62,  230,   62,   62,  231,  310,  234,
      310,  233,  310,  237,  310,  236,   62,   62,  310,  235,
       62,   62,   62,   62,  239,   62,   62,  238,  310,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,  241,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
      240,  242,   62,   62,  246,   62,   62,  310,  245,  243,

      310,  248,  310,  247,  244,   62,   62,  310,   62,   62,
       62,   62,  310,  250,  249,   62,   62,   62,   62,   62,
       62,  310,   62,   62,   62,   62,   62,   62,  310,  251,
      253,   62,   62,  310,  252,   62,   62,   62,   62,  310,
      255,  257,  256,  254,   62,   62,   62,   62,  310,  258,
       62,   62,   62,   62,  310,  259,  260,   62,   62,  310,
       62,   62,  262,  261,   62,   62,  263,   62,   62,   62,
       62,   62,   62,  310,  264,  266,   62,   62,   62,   62,
      310,  265,   62,   62,   62,   62,   62,   62,   62,   62,
      310,  267,  310,  271,  310,  273,   62,   62,   62,   62,

       62,   62,  268,  275,   62,   62,  310,  269,  310,  270,
       62,   62,  310,  272,   62,   62,   62,   62,  274,   62,
       62,  276,   62,   62,  310,  278,  310,  277,  310,  279,
       62,   62,  310,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,  281,  282,   62,
       62,  280,   62,   62,  284,   62,   62,  286,   62,   62,
      288,   62,   62,   62,   62,   62,   62,  310,  289,  310,
      283,  285,   62,   62,  287,   62,   62,   62,   62,  310,
      290,  310,  293,   62,   62,   62,   62,  310,  291,  294,
      310,  292,  310,   62,   62,   62,   62,   62,   62,  310,

       62,   62,  296,   62,   62,  310,  295,  298,   62,   62,
       62,   62,   62,   62,   62,   62,  297,   62,   62,  310,
      300,   62,   62,  301,  299,  304,  310,  302,   62,   62,
       62,   62,  303,   62,   62,  310,  305,  310,   62,   62,
       62,   62,   62,   62,  310,  306,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  308,  310,  310,
      310,  307,  309,   50,   50,  110,  110,  110,    3,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,

      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310
    } ;

static yyconst flex_int16_t yy_chk[1025] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   17,   17,   19,  314,   19,
       19,   24,   24,   27,   27,  312,   28,   28,  110,   29,
       29,   38,   38,   30,   30,   27,   27,   31,   31,   32,
       32,   33,   33,   56,   27,   28,   38,   27,   31,   50,
       29,   28,   27,   27,   29,   30,   47,   33,   31,   31,

       32,   23,   31,   34,   34,   33,   22,   30,   35,   35,
       36,   36,   21,   37,   37,   39,   39,   40,   40,   43,
       43,   18,   41,   41,   34,   36,   16,   42,   42,   35,
       43,   36,   37,   41,   43,   14,   40,   41,   37,   39,
       10,   41,   44,   44,   43,   40,   42,   43,   42,   45,
       45,   55,   55,   42,   42,   57,   57,   42,   58,    8,
       58,   58,   63,   63,   64,   64,   65,   65,   44,    7,
       45,   66,   66,   67,   67,   68,   68,   69,   69,   70,
       70,   71,   71,   72,   72,    3,   66,    0,   69,   73,
       73,   65,   67,   64,   68,   74,   74,    0,   72,   75,

       75,   77,   77,    0,   78,   78,    0,   70,   79,   79,
       71,   80,   80,   81,   81,   82,   82,    0,   75,   78,
       73,    0,   73,   77,   74,   83,   83,    0,   81,    0,
       84,   84,    0,   79,   85,   85,   86,   86,    0,   80,
        0,   87,   87,    0,   83,   84,   88,   88,    0,   85,
       89,   89,   86,   90,   90,   83,   87,   91,   91,    0,
       88,   92,   92,    0,   90,   93,   93,   94,   94,   95,
       95,   96,   96,   97,   97,   98,   98,    0,   99,   99,
        0,   89,   95,    0,   93,  100,  100,    0,   96,   99,
       98,   94,  101,  101,    0,   92,    0,   97,  102,  102,

      103,  103,  104,  104,  105,  105,  106,  106,    0,  107,
      107,  112,  112,  100,  113,  113,    0,  106,  114,  114,
      101,    0,  102,  105,  107,  115,  115,  116,  116,  117,
      117,  118,  118,  104,  103,  105,  119,  119,  120,  120,
      121,  121,  122,  122,  123,  123,    0,  114,    0,  119,
      116,  124,  124,  117,  122,  118,  125,  125,  126,  126,
      115,  127,  127,  128,  128,    0,  124,    0,  123,  129,
      129,  130,  130,  131,  131,  121,  132,  132,  133,  133,
      134,  134,  135,  135,  136,  136,  125,  126,  128,    0,
      137,  137,  138,  138,  139,  139,  127,  140,  140,  141,

      141,    0,  129,  131,  137,    0,  130,  143,  143,    0,
      142,  142,  135,  133,    0,  134,  144,  144,    0,  136,
      140,  138,  139,  141,  142,  145,  145,  146,  146,  147,
      147,  148,  148,    0,  144,  149,  149,  143,  150,  150,
      151,  151,  147,  152,  152,    0,  153,  153,  154,  154,
      155,  155,  156,  156,  149,    0,  152,  153,  157,  157,
        0,  148,  146,  154,  158,  158,  159,  159,  160,  160,
      151,  161,  161,  162,  162,  163,  163,  159,  155,  164,
      164,  165,  165,  166,  166,  167,  167,  156,  168,  168,
      169,  169,  165,  170,  170,  162,  171,  171,  172,  172,

        0,  164,    0,  168,  173,  173,    0,  171,  174,  174,
      175,  175,    0,  176,  176,  177,  177,  178,  178,  179,
      179,  170,    0,  173,  176,  180,  180,  181,  181,  182,
      182,  183,  183,    0,  179,    0,  176,    0,  181,  178,
      184,  184,  185,  185,  186,  186,  187,  187,  188,  188,
        0,  184,  189,  189,  190,  190,  183,  191,  191,  182,
        0,  187,  192,  192,  193,  193,  190,  194,  194,  195,
      195,    0,  185,  196,  196,  191,  189,  197,  197,  198,
      198,  199,  199,  200,  200,    0,  192,  201,  201,  202,
      202,    0,  197,    0,  198,  194,  203,  203,  204,  204,

      205,  205,    0,  196,  206,  206,    0,  203,    0,  199,
      207,  207,  208,  208,  209,  209,    0,  202,    0,  206,
      207,  210,  210,  211,  211,  205,  204,    0,  212,  212,
      213,  213,  214,  214,  215,  215,  217,  217,  208,  212,
      216,  216,  218,  218,  210,  219,  219,  211,    0,  214,
        0,  212,    0,  217,    0,  216,  220,  220,    0,  215,
      221,  221,  222,  222,  219,  223,  223,  218,    0,  224,
      224,  225,  225,  226,  226,  227,  227,  229,  229,  223,
      228,  228,  230,  230,  231,  231,  232,  232,  233,  233,
      222,  224,  234,  234,  228,  235,  235,    0,  227,  225,

        0,  231,    0,  228,  226,  236,  236,    0,  237,  237,
      238,  238,    0,  233,  232,  239,  239,  240,  240,  241,
      241,    0,  242,  242,  243,  243,  244,  244,    0,  235,
      237,  245,  245,    0,  236,  246,  246,  247,  247,    0,
      239,  242,  240,  238,  248,  248,  249,  249,    0,  243,
      250,  250,  251,  251,    0,  244,  245,  252,  252,    0,
      253,  253,  247,  246,  254,  254,  248,  255,  255,  256,
      256,  257,  257,    0,  249,  253,  258,  258,  259,  259,
        0,  250,  260,  260,  261,  261,  262,  262,  263,  263,
        0,  255,    0,  259,    0,  261,  264,  264,  265,  265,

      266,  266,  256,  263,  267,  267,    0,  257,    0,  258,
      268,  268,    0,  260,  269,  269,  270,  270,  262,  271,
      271,  264,  272,  272,    0,  269,    0,  265,    0,  271,
      273,  273,    0,  274,  274,  275,  275,  276,  276,  277,
      277,  278,  278,  279,  279,  280,  280,  273,  274,  281,
      281,  272,  282,  282,  277,  283,  283,  279,  284,  284,
      280,  285,  285,  286,  286,  287,  287,    0,  284,    0,
      276,  278,  288,  288,  279,  289,  289,  290,  290,    0,
      285,    0,  288,  291,  291,  292,  292,    0,  286,  289,
        0,  287,    0,  293,  293,  294,  294,  295,  295,    0,

      298,  298,  290,  296,  296,    0,  289,  293,  297,  297,
      299,  299,  300,  300,  301,  301,  291,  302,  302,    0,
      294,  303,  303,  295,  293,  298,    0,  296,  304,  304,
      305,  305,  297,  306,  306,    0,  299,    0,  307,  307,
      308,  308,  309,  309,    0,  300,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  306,    0,    0,
        0,  304,  307,  311,  311,  313,  313,  313,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,

      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gpl.l"
/*  // GPL.L
 *   Lexical scanner. scans for tokens that are used in GPL.
 *  
 *         (BISON uses tokens generated from this file to match 
 *          grammer and take specific actions) (see gpl.y)
 *
*
 */
/*
	 Use the following global variable to retrieve the current symbol (the one
	 just read):

	 char *yytext               //

	 Use the following global variable to send information back to main():

	 extern YYSTYPE yylval;

	 The union YYSTYPE is defined in y.tab.h (which is included by parser.h).
	 You can use a union just like a struct (which is a lot like a class),
	 except that only one member variable can be used at a time.
	 y.tab.h is generated by bison from expr.y.

 */
#line 29 "gpl.l"

#include "error.h"    // GPL specific error funcs()
#include "parser.h"   

#include <ctype.h>
#include <iostream>
	using namespace std;

	Error error_handler; // error reporting object

	// The following variable keeps track of what input line flex is reading.
	// It will be used (by other parts of the program) for reporting the line
	// numbers of errors.
	// It will be used by other parts of the program via the extern construct
	//   If another .cpp file declares "extern int line_count" that line_count
	//   in that file will be the line_count in this file (it becomes global)
	int line_count = 1;

	int 
	emit_int(int token)
	{
		// convert the string yytext into an integer
		// put it into the global union used to send values to the parser (.y file)
		// the union is declared in the .y file
		yylval.union_int = atoi(yytext);

		return token;
	}

	// **********************************************************************
	// sets the union_double to the double that yytext contains 
	//   since yytext was matched with expression and this func is called
	//   returns token that bison needs in order to know that a double value was read
	int 
	emit_double(int token){
		// matched "text" needs to be converted to double in order to do calc
		yylval.union_double = atof(yytext); // value union's "double" is set to the input
		return token;
	}


	// ********************************************************************** 
	// when string is matched this is called and sets A NEW string appropriately.
	// an accompanying token is returned.
	int 
	emit_string(int token){
		yylval.union_string = new string(yytext+1, strlen(yytext)-2);
		return token;
	}



	// ********************************************************************** 
	// stores the identifier name for a variable (ASSOCIATED WITH T_ID)
	int
	emit_identifier(int token){
		yylval.union_string = new string(yytext, strlen(yytext));
		return token;
	}

	int 
	emit_error(int token)
	{
		// have the error handling object report the problem
		// note: it uses line_count as a global variable
		error_handler.error(Error::ILLEGAL_TOKEN, yytext);

		// create a string to hold the current text
		// put that string in the yylval union so it can be used by parser (.y file)
		yylval.union_string = new string(yytext);
		return token;
	}


	int
	emit_with_line_number(int token){
		 yylval.union_int = line_count;
	   return token;
	}
	
#line 891 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 112 "gpl.l"


#line 1081 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 311 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 969 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 114 "gpl.l"
line_count++; // count the lines for error reporting
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 115 "gpl.l"
;  // ignore spaces, tabs and the line feed (\r)
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 117 "gpl.l"
line_count++;  // ignore ocmments  
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 123 "gpl.l"
return(T_INT);         //objects
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 124 "gpl.l"
return(T_DOUBLE);	
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 125 "gpl.l"
return(T_STRING);						
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 "gpl.l"
return(T_TRIANGLE);	
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 127 "gpl.l"
return(T_PIXMAP);	
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 128 "gpl.l"
return(T_CIRCLE);	
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "gpl.l"
return(T_RECTANGLE);	
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 130 "gpl.l"
return(T_TEXTBOX);	
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 132 "gpl.l"
return(T_FORWARD);  // keywords
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 133 "gpl.l"
return(T_INITIALIZATION);	
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 134 "gpl.l"
return(T_ON);	
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 135 "gpl.l"
return(T_ANIMATION);	
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 136 "gpl.l"
return(T_IF);	
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 137 "gpl.l"
return(T_FOR);	
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 138 "gpl.l"
return(T_ELSE);	
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 139 "gpl.l"
return emit_with_line_number(T_EXIT);	
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 140 "gpl.l"
return emit_with_line_number(T_PRINT);	
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 141 "gpl.l"
return(T_TRUE);	
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 142 "gpl.l"
return(T_FALSE);  // const values set in bison 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 144 "gpl.l"
return(T_SPACE); // event keys
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 145 "gpl.l"
return(T_LEFTARROW );	
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 146 "gpl.l"
return(T_RIGHTARROW );	
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 147 "gpl.l"
return(T_UPARROW );	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 148 "gpl.l"
return(T_DOWNARROW );	
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 149 "gpl.l"
return(T_LEFTMOUSE_DOWN );	
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 150 "gpl.l"
return(T_MIDDLEMOUSE_DOWN );	
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 151 "gpl.l"
return(T_RIGHTMOUSE_DOWN );	
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 152 "gpl.l"
return(T_LEFTMOUSE_UP );	
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 153 "gpl.l"
return(T_MIDDLEMOUSE_UP );	
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 154 "gpl.l"
return(T_RIGHTMOUSE_UP );	
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 155 "gpl.l"
return(T_MOUSE_MOVE );	
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 156 "gpl.l"
return(T_MOUSE_DRAG );	
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 157 "gpl.l"
return(T_F1 );	
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 158 "gpl.l"
return(T_AKEY );	
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 159 "gpl.l"
return(T_SKEY );	
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 160 "gpl.l"
return(T_DKEY );	
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 161 "gpl.l"
return(T_FKEY );	
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 162 "gpl.l"
return(T_HKEY );	
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 163 "gpl.l"
return(T_JKEY );	
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 164 "gpl.l"
return(T_KKEY );	
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 165 "gpl.l"
return(T_LKEY );	
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 166 "gpl.l"
return(T_WKEY );	
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 168 "gpl.l"
return(T_LPAREN ); 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 169 "gpl.l"
return(T_RPAREN);	
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 170 "gpl.l"
return(T_LBRACE);	
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 171 "gpl.l"
return(T_RBRACE);	
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 172 "gpl.l"
return(T_LBRACKET);	
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 173 "gpl.l"
return(T_RBRACKET);	
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 174 "gpl.l"
return(T_SEMIC);	
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 175 "gpl.l"
return(T_COMMA);	
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 176 "gpl.l"
return(T_PERIOD);	
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 178 "gpl.l"
return(T_ASSIGN); 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 179 "gpl.l"
return(T_PLUS_ASSIGN);	
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 180 "gpl.l"
return(T_MINUS_ASSIGN);	
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 182 "gpl.l"
return(T_SIN ); 
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 183 "gpl.l"
return(T_COS );	
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 184 "gpl.l"
return(T_TAN );	
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 185 "gpl.l"
return(T_ASIN );	
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 186 "gpl.l"
return(T_ACOS );	
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 187 "gpl.l"
return(T_ATAN );	
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 188 "gpl.l"
return(T_SQRT );	
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 189 "gpl.l"
return(T_ABS );	
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 190 "gpl.l"
return(T_FLOOR );	
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 191 "gpl.l"
return(T_RANDOM );	
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 193 "gpl.l"
return(T_TOUCHES );
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 194 "gpl.l"
return(T_NEAR );	
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 197 "gpl.l"
return(T_ASTERISK); 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 198 "gpl.l"
return(T_DIVIDE);	
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 199 "gpl.l"
return(T_PLUS);	
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 200 "gpl.l"
return(T_MINUS);	
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 201 "gpl.l"
return(T_MOD);	
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 204 "gpl.l"
return(T_LESS); 
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 205 "gpl.l"
return(T_GREATER);	
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 206 "gpl.l"
return(T_LESS_EQUAL);	
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 207 "gpl.l"
return(T_GREATER_EQUAL);	
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 208 "gpl.l"
return(T_EQUAL);	
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 209 "gpl.l"
return(T_NOT_EQUAL);	
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 210 "gpl.l"
return(T_NOT);	
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 211 "gpl.l"
return(T_AND);	
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 212 "gpl.l"
return(T_OR);	
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 215 "gpl.l"
return emit_int(T_INT_CONSTANT);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 216 "gpl.l"
return emit_double(T_DOUBLE_CONSTANT); 
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 217 "gpl.l"
{ return emit_string(T_STRING_CONSTANT);} // empty string
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 218 "gpl.l"
{ return emit_string(T_STRING_CONSTANT);} // a string
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 219 "gpl.l"
{ return emit_identifier(T_ID);}          // a variable.. 
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 221 "gpl.l"
{}; // ignore the rest.. else it just prints out  "'s everywhere...

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 224 "gpl.l"
ECHO;
	YY_BREAK
#line 1618 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 311 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 311 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 310);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "gpl.l"
